# This workflow will run tests on PRs that start with 'feat/' or 'fix/'.
name: Classic Phone Pad PR
on:
  pull_request:
    branches:
      - main
jobs:
  build_test:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feat/') || startsWith(github.head_ref, 'fix/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-restore --configuration Release --verbosity normal
